name: Run fabric-agent-action on issue comment
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  fabric_agent_action:
    name: Run fabric-agent-action on issue comment
    if: >
      github.event.comment.user.login == 'xvnpw' &&
      startsWith(github.event.comment.body, '/fabric') &&
      !github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: read-issue-and-comment-script
        with:
          result-encoding: string
          retries: 3
          script: |
            const issue = await github.rest.issues.get({
              issue_number: ${{ github.event.issue.number }},
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
            });
            const issueBody = issue.data.body;

            const comment = await github.rest.issues.getComment({
              comment_id: ${{ github.event.comment.id }},
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
            });
            const commentBody = comment.data.body;

            const fabric_input = commentBody + "\n\n" + "GitHub issue:\n" + issueBody;

            const fs = require('fs');
            fs.writeFileSync('${{ github.workspace }}/fabric_input.md', fabric_input, (err) => {
                if (err) throw err;
                console.log('Data written to file');
            });
            return JSON.stringify(fabric_input);
      - name: Run fabric-agent-action
        uses:  docker://ghcr.io/xvnpw/fabric-agent-action:v0.0.17
        with:
          input_file: "fabric_input.md"
          output_file: "fabric_output.md"
          fabric_provider: "openrouter"
          fabric_model: "openai/o1-preview"
          fabric_temperature: 0.2
          fabric_tools_included: "clean_text,create_stride_threat_model,create_design_document,review_design,refine_design_document,create_threat_scenarios,improve_writing,create_quiz,create_summary"
          debug: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body-path: ${{ github.workspace }}/fabric_output.md
